services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\DoctrineSimpleTranslationTypeBundle\Twig\Extension\:
        resource: '../../src/Twig/Extension/*'
        tags: ['twig.extension']
